### ISSUE TITLE
Using Python 3 scripts to get stock quotes

### ISSUE THREAD

**Issue by jrseattle** [magnuspyke/ofxscripts#1]
Trying to run setup.py to test stock quotes using Python 3.12. Get this error:

1.  Stock/Fund Prices
0.  None
------------------------------
Test account #: [0] 1
Test Stock/Fund Pricing Updates (Y/N)? y
Getting security and fund quotes
Getting quote for: ^GSPC
^GSPC: 4358.34 11/03/2023 14:00:32 0.94%
Getting quote for: ^IXIC
^IXIC: 13478.28 11/03/2023 14:15:59 1.38%
Getting quote for: BP.L
BP.L: 4.90 11/03/2023 10:27:06 -1.75%
Getting quote for: GOOG
GOOG: 130.37 11/03/2023 13:00:01 1.39%
Getting quote for: YHOO
** YHOO: invalid quote response. Skipping.
Getting quote for: EURUSD=X
EURUSD=X: 1.07 11/03/2023 14:29:42 0.9657%
Getting quote for: USDJPY=X
USDJPY=X: 149.33 11/03/2023 13:59:56 -0.7471%
Getting quote for: MBFIX
MBFIX: 10.61 11/03/2023 17:00:35 0.66%
Getting quote for: AGTHX
AGTHX: 60.28 11/03/2023 17:01:07 1.41%
Traceback (most recent call last):
  File "C:\Users\jrsea\Documents\Money\Pocketsense\ofxscripts-main-v3\setup.py", line 408, in <module>
    test_quotes()
  File "C:\Users\jrsea\Documents\Money\Pocketsense\ofxscripts-main-v3\setup.py", line 222, in test_quotes
    status, ofxFile1, ofxFile2, htmFile = quotes.getQuotes()
                                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jrsea\Documents\Money\Pocketsense\ofxscripts-main-v3\quotes.py", line 436, in getQuotes
    ofxFile1 = xfrdir + "quotes" + dateTimeStr() + str(random.randrange(1e5,1e6)) + ".ofx"
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jrsea\AppData\Local\Programs\Python\Python312\Lib\random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

**Comment by magnuspyke** [comment]
Seems something changed in random.randrange() in python 3.12.  I changed the E notation in the code to integer notation and it seems to work fine now.

**Comment by jrseattle** [comment]
Thanks. It works great now.

JdR
